-> Bind method changed: What: Included hat type for return parameter. Why: To help type inference. Code like: let getStringAtleast8Chars:MaybeT<_> =  lift getLine >>= fun s -> (guard (String.length s >= 8) ) >>= fun _ -> return' s in order to compile will require and addition type annotation for the result of the Bind method. This way if type inference knows the result type of the whole function, can infer the type of the Bind.
-> Include previously curried parameter in function ap.
Why: This way the second parameter gets included in the resolution.
Otherwise the method ap for the Typeclass ListT will not compile and will say:
MonadTrans.fs(50,89): error FS0073: internal error: Undefined or unsolved type variable:  ^_?1266953

-> Added sample/test code